// <auto-generated />
namespace eCommerceS2B_2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class atualizaçao2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualizaçao2));
        
        string IMigrationMetadata.Id
        {
            get { return "201610060636472_atualizaçao2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
